/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "SUP101SISSubscriptionKey.h"
#import "SUP101SISSubscriptionKeyMetaData.h"
#import "SUP101SUP101DB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"
@implementation SUP101SISSubscriptionKey

static SUPClassDelegate *g_SUP101SISSubscriptionKey_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_SUP101SISSubscriptionKey_delegate == nil) {
			g_SUP101SISSubscriptionKey_delegate = [[SUPClassDelegate alloc] initWithName:@"SUP101SISSubscriptionKey" clazz:[self class]
				metaData:[self metaData] dbDelegate:[SUP101SUP101DB delegate] database:[SUP101SUP101DB instance]];
		}
	}
	
	return [[g_SUP101SISSubscriptionKey_delegate retain] autorelease];
}
static SUPClassMetaDataRBS* SUP101SISSubscriptionKey_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (SUP101SISSubscriptionKey_META_DATA == nil) {
 	   	SUP101SISSubscriptionKey_META_DATA = [[SUP101SISSubscriptionKeyMetaData alloc] init];
	}
	
	return SUP101SISSubscriptionKey_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

@end