/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "SUP101SISSubscription.h"
#import "SUP101SISSubscriptionMetaData.h"
#import "SUP101SUP101DB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
@implementation SUP101SISSubscription

static SUPEntityDelegate *g_SUP101SISSubscription_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_SUP101SISSubscription_delegate == nil) {
			g_SUP101SISSubscription_delegate = [[SUPEntityDelegate alloc] initWithName:@"SUP101SISSubscription" clazz:[self class]
				metaData:[self metaData] dbDelegate:[SUP101SUP101DB delegate] database:[SUP101SUP101DB instance]];
		}
	}
	
	return [[g_SUP101SISSubscription_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* SUP101SISSubscription_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (SUP101SISSubscription_META_DATA == nil) {
		SUP101SISSubscription_META_DATA = [[SUP101SISSubscriptionMetaData alloc] init];
	}
	
	return SUP101SISSubscription_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

@end