/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "SUP101LocalKeyGenerator.h"
#import "SUP101LocalKeyGeneratorMetaData.h"
#import "SUPLocalEntityDelegate.h"
#import "SUP101SUP101DB.h"
#import "SUPEntityDelegate.h"
#import "SUPLocalKeyGenerator.h"

@implementation SUP101LocalKeyGenerator

static SUPLocalEntityDelegate *g_SUP101LocalKeyGenerator_delegate = nil;

+ (SUPLocalEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_SUP101LocalKeyGenerator_delegate == nil) {
			g_SUP101LocalKeyGenerator_delegate = [[SUPLocalEntityDelegate alloc] initWithName:@"SUP101LocalKeyGenerator" clazz:[self class]
				metaData:[self metaData] dbDelegate:[SUP101SUP101DB delegate] database:[SUP101SUP101DB instance]];
		}
	}
	
	return [[g_SUP101LocalKeyGenerator_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* SUP101LocalKeyGenerator_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (SUP101LocalKeyGenerator_META_DATA == nil) {
 	   	SUP101LocalKeyGenerator_META_DATA = [[SUP101LocalKeyGeneratorMetaData alloc] init];
	}
	
	return SUP101LocalKeyGenerator_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (id)init
{
    self = [super initWithParameters:[SUP101SUP101DB delegate]:@"co_sup101_1_0_localkeygenerator":100000];
    if (self) {
        // Initialization code here.
        [SUPLocalKeyGenerator setObjectInstance:@"SUP101":self];
    }
    
    return self;
}

+ (SUP101LocalKeyGenerator*)getInstance
{
    SUP101LocalKeyGenerator* me = [[SUP101LocalKeyGenerator alloc] init];
    [me autorelease];
    return me;
}

+ (int64_t)generateId
{
    return [[SUP101SUP101DB delegate] generateLocalId];
}

@end