/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "SUP101ChangeLogImpl.h"
#import "SUP101ChangeLogImplMetaData.h"
#import "SUPJsonObject.h"
#import "SUP101SUP101DB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "SUP101KeyGenerator.h"
#import "SUP101LocalKeyGenerator.h"
#import "SUP101LogRecordImpl.h"
#import "SUPConnectionWrapper.h"
#import "SUPLocalTransaction.h"
#import "SUPStatementWrapper.h"

@implementation SUP101ChangeLogImpl

@synthesize operationType = _operationType;
@synthesize rootEntityType = _rootEntityType;
@synthesize rootSurrogateKey = _rootSurrogateKey;
@synthesize entityType = _entityType;
@synthesize surrogateKey = _surrogateKey;

- (int32_t)entityType
{
    return _entityType;
}

- (int64_t)surrogateKey
{
    return _surrogateKey;
}

- (void)setOperationType:(unichar)newOperationType
{
    if (newOperationType != self->_operationType)
    {
        self->_operationType = newOperationType;
        self.isDirty = YES;
    }
}

- (void)setRootEntityType:(int32_t)newRootEntityType
{
    if (newRootEntityType != self->_rootEntityType)
    {
        self->_rootEntityType = newRootEntityType;
        self.isDirty = YES;
    }
}

- (void)setRootSurrogateKey:(int64_t)newRootSurrogateKey
{
    if (newRootSurrogateKey != self->_rootSurrogateKey)
    {
        self->_rootSurrogateKey = newRootSurrogateKey;
        self.isDirty = YES;
    }
}

- (void)setEntityType:(int32_t)newEntityType
{
    if (newEntityType != self->_entityType)
    {
        self->_entityType = newEntityType;
        self.isNew = YES;
    }
}

- (void)setSurrogateKey:(int64_t)newSurrogateKey
{
    if (newSurrogateKey != self->_surrogateKey)
    {
        self->_surrogateKey = newSurrogateKey;
        self.isNew = YES;
    }
}

static SUPEntityDelegate *g_SUP101ChangeLogImpl_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_SUP101ChangeLogImpl_delegate == nil) {
			g_SUP101ChangeLogImpl_delegate = [[SUPEntityDelegate alloc] initWithName:@"SUP101ChangeLogImpl" clazz:[self class]
				metaData:[self metaData] dbDelegate:[SUP101SUP101DB delegate] database:[SUP101SUP101DB instance]];
		}
	}
	
	return [[g_SUP101ChangeLogImpl_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* SUP101ChangeLogImpl_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (SUP101ChangeLogImpl_META_DATA == nil) {
		SUP101ChangeLogImpl_META_DATA = [[SUP101ChangeLogImplMetaData alloc] init];
	}
	
	return SUP101ChangeLogImpl_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [SUP101ChangeLogImpl metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[SUP101ChangeLogImpl delegate]];
    }
    return self;    
}

- (void)dealloc
{
	[super dealloc];
}




+ (SUP101ChangeLogImpl*)find:(SUP101ChangeLogKey*)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:[NSNumber numberWithInt:id_.entityType]];
    [keys add:[NSNumber numberWithLong:id_.surrogateKey]];
    return (SUP101ChangeLogImpl*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

+ (SUPObjectList*)findWithQuery:(SUPQuery*)query
{
    return (SUPObjectList*)[(SUPEntityDelegate*)([[self class] delegate])  findWithQuery:query:[SUP101ChangeLogImpl class]];
}

- (SUP101ChangeLogKey*)_pk
{
    return (SUP101ChangeLogKey*)[self i_pk];
}

+ (SUP101ChangeLogImpl*)load:(SUP101ChangeLogKey*)id_
{
    return (SUP101ChangeLogImpl*)[(SUPEntityDelegate*)([[self class] delegate]) load:id_];
}

+ (SUP101ChangeLogImpl*)getInstance
{
    SUP101ChangeLogImpl* me = [[SUP101ChangeLogImpl alloc] init];
    [me autorelease];
    return me;
}
- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 81:
        return self.rootSurrogateKey;
    case 78:
        return self.surrogateKey;
    default:
         return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 81:
        self.rootSurrogateKey = v;
        break;;
    case 78:
        self.surrogateKey = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPChar) getAttributeChar:(int)id_
{
    switch(id_)
    {
    case 79:
        return self.operationType;
    default:
         return [super getAttributeChar:id_];
    }
}

-(void) setAttributeChar:(int)id_:(SUPChar)v
{
    switch(id_)
    {
    case 79:
        self.operationType = v;
        break;;
    default:
        [super setAttributeChar:id_:v];
        break;;
    }
}
-(SUPInt) getAttributeInt:(int)id_
{
    switch(id_)
    {
    case 80:
        return self.rootEntityType;
    case 77:
        return self.entityType;
    default:
         return [super getAttributeInt:id_];
    }
}

-(void) setAttributeInt:(int)id_:(SUPInt)v
{
    switch(id_)
    {
    case 80:
        self.rootEntityType = v;
        break;;
    case 77:
        self.entityType = v;
        break;;
    default:
        [super setAttributeInt:id_:v];
        break;;
    }
}
- (SUPObjectList*)getLogRecords
{
   return [SUP101LogRecordImpl findByEntity:@"ChangeLogImpl":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	ChangeLogImpl = \n\
	    operationType = %c,\n\
	    rootEntityType = %i,\n\
	    rootSurrogateKey = %qi,\n\
	    entityType = %i,\n\
	    surrogateKey = %qi,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.operationType
    	,self.rootEntityType
    	,self.rootSurrogateKey
    	,self.entityType
    	,self.surrogateKey
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}


+ (void) deleteChangeLogs
{
    NSString *sql = @"truncate table sup101_1_0_changelogimpl";
    id<SUPConnectionWrapper> connection = nil;
    id<SUPStatementWrapper> preparedStatement = nil;
    SUPLocalTransaction* transaction = nil;
    BOOL ok = NO;
    @try
    {
        [[SUP101SUP101DB dblock] writeLock];
        connection = [SUP101SUP101DB getConnectionWrapper];
        transaction = ([connection inTransaction] ? nil : [SUP101SUP101DB beginTransaction]);
        preparedStatement = [connection prepareStatement:sql];
        [preparedStatement execute];
     	ok = YES;
    }
    @catch (NSException *e) {
        ok = NO;
        @throw e;
    }
    @finally {
        [preparedStatement close];
        if (ok)
        {
            [transaction commit];
        }
        else
        {
            [transaction rollback];
        }
        [connection releaseToPool];
        [[SUP101SUP101DB dblock] unlock];
    }    
    
}


/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query
{
    return [(SUPEntityDelegate*)([[self class] delegate]) getSize:query];
}

@end