#import "SUPAbstractLogger.h"

/*!
 @class SUP101LoggerImpl
 @abstract This class is part of package "SUP101:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/ 

@interface SUP101LoggerImpl: SUPAbstractLogger

@end