#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPSISSubscription.h"


@class SUPEntityMetaDataRBS;
@class SUPEntityDelegate;
@class SUPClassMetaDataRBS;
#import "SUP101SISSubscriptionKey.h"

// public interface declaration, can be used by application. 
/*!
 @class SUP101SISSubscription
 @abstract This class is part of package "SUP101:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/

@interface SUP101SISSubscription : SUPSISSubscription<SUPClassWithMetaData>
{
}
+ (SUPEntityMetaDataRBS*)metaData;
+ (SUPEntityDelegate *)delegate;
/*!
  @method 
  @abstract Sets relationship attributes to null to save memory (they will be retrieved from the DB on the next getter call or property reference)
  @discussion
  @throws SUPPersistenceException
 */
- (void)clearRelationshipObjects;


@end