/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "SUP101KeyPackageName.h"
#import "SUP101KeyPackageNameMetaData.h"
#import "SUPJsonObject.h"
#import "SUP101SUP101DB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"

@implementation SUP101KeyPackageName

@synthesize key_name = _key_name;
@synthesize package_name = _package_name;
@synthesize user_name = _user_name;
@synthesize domain_name = _domain_name;

static SUPClassDelegate *g_SUP101KeyPackageName_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_SUP101KeyPackageName_delegate == nil) {
			g_SUP101KeyPackageName_delegate = [[SUPClassDelegate alloc] initWithName:@"SUP101KeyPackageName" clazz:[self class]
				metaData:[self metaData] dbDelegate:[SUP101SUP101DB delegate] database:[SUP101SUP101DB instance]];
		}
	}
	
	return [[g_SUP101KeyPackageName_delegate retain] autorelease];
}

static SUPClassMetaDataRBS* SUP101KeyPackageName_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (SUP101KeyPackageName_META_DATA == nil) {
 	   	SUP101KeyPackageName_META_DATA = [[SUP101KeyPackageNameMetaData alloc] init];
	}
	
	return SUP101KeyPackageName_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[SUP101KeyPackageName metaData];
        [self setClassDelegate:[[self class] delegate]];
        
    }
    return self;    
}

-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 90:
        return self.key_name;
    case 92:
        return self.package_name;
    case 91:
        return self.user_name;
    case 93:
        return self.domain_name;
    default:
        return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 90:
        self.key_name = v;
        break;;
    case 92:
        self.package_name = v;
        break;;
    case 91:
        self.user_name = v;
        break;;
    case 93:
        self.domain_name = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
+ (SUP101KeyPackageName*)getInstance
{
    SUP101KeyPackageName* me = [[SUP101KeyPackageName alloc] init];
    [me autorelease];
    return me;
}
- (void)dealloc
{
    if(_key_name)
    {
        [_key_name release];
        _key_name = nil;
    }
    if(_package_name)
    {
        [_package_name release];
        _package_name = nil;
    }
    if(_user_name)
    {
        [_user_name release];
        _user_name = nil;
    }
    if(_domain_name)
    {
        [_domain_name release];
        _domain_name = nil;
    }
	[super dealloc];
}

@end