#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPAbstractEntityRBS.h"
#import "SUPMobileBusinessObject.h"
#import "SUPEntityDelegate.h"


@class SUPObjectList;
@class SUPEntityMetaDataRBS;
@class SUPEntityDelegate;
@class SUPClassMetaDataRBS;
@class SUPQuery;

// public interface declaration, can be used by application. 
/*!
 @class SUP101Customer
 @abstract This class is part of package "SUP101:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/

@interface SUP101Customer : SUPAbstractEntityRBS<SUPMobileBusinessObject, SUPClassWithMetaData>
{
@private
    int32_t _id;
    NSString* _fname;
    NSString* _lname;
    NSString* _address;
    NSString* _city;
    NSString* _state;
    NSString* _zip;
    NSString* _phone;
    NSString* _company_name;
    SUPObjectList* _customerSalesOrders;
    int64_t _surrogateKey;
}

@property(assign,nonatomic) int32_t id_;
@property(retain,nonatomic) NSString* fname;
@property(retain,nonatomic) NSString* lname;
@property(retain,nonatomic) NSString* address;
@property(retain,nonatomic) NSString* city;
@property(retain,nonatomic) NSString* state;
@property(retain,nonatomic) NSString* zip;
@property(retain,nonatomic) NSString* phone;
@property(retain,nonatomic) NSString* company_name;
@property(retain,nonatomic) SUPObjectList* customerSalesOrders;
@property(assign,nonatomic) int64_t surrogateKey;

+ (SUPEntityMetaDataRBS*)metaData;
+ (SUPEntityDelegate *)delegate;
+ (void) registerCallbackHandler:(NSObject<SUPCallbackHandler>*)handler;
+ (NSObject<SUPCallbackHandler>*)callbackHandler;
- (SUPClassMetaDataRBS*)getClassMetaData;
/*!
  @method 
  @abstract Sets relationship attributes to null to save memory (they will be retrieved from the DB on the next getter call or property reference)
  @discussion
  @throws SUPPersistenceException
 */
- (void)clearRelationshipObjects;
- (id) init;
- (void)dealloc;
/*!
  @method 
  @abstract Returns the entity for the primary key value passed in, or null if the entity is not found.
  @discussion
  @throws SUPPersistenceException
 */
+ (SUP101Customer*)find:(int64_t)id_;
/*!
  @method 
  @abstract Returns an SUPObjectList of entity rows satisfying this query
  @discussion
  @throws SUPPersistenceException
 */
+ (SUPObjectList*)findWithQuery:(SUPQuery*)query;
/*!
  @method 
  @abstract Returns the primary key for this entity.
  @discussion
 */
- (int64_t)_pk;
/*!
  @method 
  @abstract Returns the entity for the primary key value passed in; throws an exception if the entity is not found.
  @discussion
  @throws SUPPersistenceException
 */
+ (SUP101Customer*)load:(int64_t)id;
/*!
  @method 
  @abstract Returns an SUPObjectList of log records for this entity.
  @discussion
  @throws SUPPersistenceException
 */
- (SUPObjectList*)getLogRecords;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (SUP101Customer*)getInstance;
/*!
  @method 
  @abstract Return a string description of this entity.
  @discussion
 */
- (NSString*)toString;
/*!
  @method 
  @abstract Return a string description of this entity.
  @discussion
 */
- (NSString*)description;
+ (void) submitPendingOperations;
+ (void) cancelPendingOperations;
- (SUPString)getLastOperation;
+ (SUPObjectList*)getPendingObjects;
+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @throws SUPPersistenceException
 */

+ (SUPObjectList*)findAll;

/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param skip
  @param take
  @throws SUPPersistenceException
 */

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param id_
  @throws SUPPersistenceException
 */

+ (SUP101Customer*)findByPrimaryKey:(int32_t)id_;
/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query;
/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param query
  @throws SUPPersistenceException
 */

- (SUPObjectList*)getCustomerSalesOrdersFilterBy:(SUPQuery*)query;

/*!
  @method
  @abstract Generated from an object query defined in the Eclipse tooling project for this package
  @param query
  @param skip
  @param take
  @throws SUPPersistenceException
 */

- (SUPObjectList*)getCustomerSalesOrdersFilterBy:(SUPQuery*)query skip:(int32_t)skip take:(int32_t)take;
/*!
  @method
  @abstract Generated instance method 
  @param query
  @throws SUPPersistenceException
 */
- (int32_t)getCustomerSalesOrdersSize:(SUPQuery*)query;


@end
typedef SUPObjectList SUP101CustomerList;

// internal methods declaration, only used by generated code.
@interface SUP101Customer(internal)


- (SUPJsonObject*)getAttributeJson:(int)id_;
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value;

-(SUPLong) getAttributeLong:(int)id_;
-(void) setAttributeLong:(int)id_:(SUPLong)v;
-(SUPString) getAttributeNullableString:(int)id_;
-(void) setAttributeNullableString:(int)id_:(SUPString)v;
-(SUPString) getAttributeString:(int)id_;
-(void) setAttributeString:(int)id_:(SUPString)v;
-(SUPInt) getAttributeInt:(int)id_;
-(void) setAttributeInt:(int)id_:(SUPInt)v;
-(id) getAttributeObject:(int)id_:(BOOL)loadFromDBIfInvalid;
-(void) setAttributeObject:(int)id_:(id)v;
@end